# Generated by Django 4.2.7 on 2026-03-01 22:49

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_type', models.CharField(choices=[('auto', 'Automatic'), ('manual', 'Manual'), ('pre_sync', 'Pre-Sync')], max_length=20)),
                ('filename', models.CharField(max_length=500)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='success', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('records_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_type', models.CharField(choices=[('camera', 'Camera Status'), ('network', 'Network Status'), ('storage', 'Storage Status'), ('sync', 'Sync Status'), ('face_recognition', 'Face Recognition Status'), ('system', 'System Health')], db_index=True, max_length=50)),
                ('key', models.CharField(max_length=100)),
                ('value', models.JSONField(default=dict)),
                ('is_healthy', models.BooleanField(default=True)),
                ('last_check', models.DateTimeField(auto_now=True)),
                ('message', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'indexes': [models.Index(fields=['status_type', 'is_healthy'], name='attendance__status__ed8ebb_idx')],
                'unique_together': {('status_type', 'key')},
            },
        ),
        migrations.CreateModel(
            name='OfflineQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('checkin', 'Check-in'), ('member_update', 'Member Update'), ('photo_upload', 'Photo Upload'), ('bulk_sync', 'Bulk Sync')], max_length=50)),
                ('priority', models.IntegerField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')], default=2)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
            ],
            options={
                'ordering': ['priority', 'created_at'],
                'indexes': [models.Index(fields=['processed', 'priority'], name='attendance__process_482a51_idx'), models.Index(fields=['created_at'], name='attendance__created_f41dc5_idx')],
            },
        ),
        migrations.CreateModel(
            name='LocalMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('last_sync', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('member_type', models.CharField(choices=[('adult', 'Adult'), ('child', 'Child')], default='adult', max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('belt_rank', models.CharField(choices=[('white', 'White'), ('blue', 'Blue'), ('purple', 'Purple'), ('brown', 'Brown'), ('black', 'Black'), ('red', 'Red'), ('gray_white', 'Gray/White'), ('gray', 'Gray'), ('gray_black', 'Gray/Black'), ('yellow_white', 'Yellow/White'), ('yellow', 'Yellow'), ('yellow_black', 'Yellow/Black'), ('orange_white', 'Orange/White'), ('orange', 'Orange'), ('orange_black', 'Orange/Black'), ('green_white', 'Green/White'), ('green', 'Green'), ('green_black', 'Green/Black')], default='white', max_length=50)),
                ('stripes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('face_registered', models.BooleanField(default=False)),
                ('face_photos_count', models.IntegerField(default=0)),
                ('face_encoding_path', models.CharField(blank=True, max_length=500, null=True)),
                ('photo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['remote_id'], name='attendance__remote__7a7045_idx'), models.Index(fields=['last_name', 'first_name'], name='attendance__last_na_fe107b_idx'), models.Index(fields=['is_active'], name='attendance__is_acti_bf6336_idx'), models.Index(fields=['face_registered'], name='attendance__face_re_7304f1_idx')],
            },
        ),
        migrations.CreateModel(
            name='FaceTrainingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos_attempted', models.IntegerField(default=0)),
                ('photos_successful', models.IntegerField(default=0)),
                ('success', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('training_data', models.JSONField(blank=True, default=dict)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_training_logs', to='attendance_app.localmember')),
                ('trained_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('members', 'Members Sync'), ('attendance', 'Attendance Sync'), ('full', 'Full Sync'), ('manual', 'Manual Sync')], max_length=50)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('records_processed', models.IntegerField(default=0)),
                ('records_succeeded', models.IntegerField(default=0)),
                ('records_failed', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial Success')], default='running', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('details', models.JSONField(default=dict)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['status'], name='attendance__status_b98d3d_idx'), models.Index(fields=['sync_type'], name='attendance__sync_ty_aba9cc_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('action_url', models.CharField(blank=True, max_length=500)),
                ('read_by', models.ManyToManyField(blank=True, related_name='read_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['read', 'created_at'], name='attendance__read_d2039b_idx'), models.Index(fields=['notification_type'], name='attendance__notific_12f1db_idx')],
            },
        ),
        migrations.CreateModel(
            name='LocalAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(default=datetime.date.today)),
                ('check_in_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('check_in_method', models.CharField(choices=[('manual', 'Manual Entry'), ('face', 'Face Recognition'), ('qr', 'QR Code'), ('nfc', 'NFC Card'), ('api', 'API'), ('bulk', 'Bulk Import')], max_length=20)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('synced', models.BooleanField(default=False)),
                ('sync_error', models.TextField(blank=True)),
                ('sync_attempts', models.IntegerField(default=0)),
                ('last_sync_attempt', models.DateTimeField(blank=True, null=True)),
                ('remote_attendance_id', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('photo_path', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='attendance_app.localmember')),
            ],
            options={
                'ordering': ['-check_in_time'],
                'indexes': [models.Index(fields=['member', 'session_date'], name='attendance__member__40853e_idx'), models.Index(fields=['synced'], name='attendance__synced_59da48_idx'), models.Index(fields=['check_in_time'], name='attendance__check_i_ea2436_idx'), models.Index(fields=['session_date'], name='attendance__session_0aec80_idx')],
                'unique_together': {('member', 'session_date')},
            },
        ),
    ]
