# Generated by Django 5.2.11 on 2026-03-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localattendance',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='localattendance',
            name='attendance__member__40853e_idx',
        ),
        migrations.RemoveIndex(
            model_name='localattendance',
            name='attendance__synced_59da48_idx',
        ),
        migrations.RemoveIndex(
            model_name='localattendance',
            name='attendance__check_i_ea2436_idx',
        ),
        migrations.RemoveIndex(
            model_name='localattendance',
            name='attendance__session_0aec80_idx',
        ),
        migrations.AlterUniqueTogether(
            name='localattendance',
            unique_together={('member', 'session_date', 'check_in_time')},
        ),
        migrations.AddField(
            model_name='localattendance',
            name='next_sync_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='localattendance',
            name='sync_error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
